/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HowToRouteImport } from './routes/how-to'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as BaseIdRouteImport } from './routes/base.$id'
import { Route as ThThRouteImport } from './routes/th.$th'
import { Route as TypeTypeRouteImport } from './routes/type.$type'
import { Route as ApiCronSyncRouteImport } from './routes/api.cron.sync'
import { Route as ThThTypeRouteImport } from './routes/th.$th.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToRoute = HowToRouteImport.update({
  id: '/how-to',
  path: '/how-to',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseIdRoute = BaseIdRouteImport.update({
  id: '/base/$id',
  path: '/base/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ThThRoute = ThThRouteImport.update({
  id: '/th/$th',
  path: '/th/$th',
  getParentRoute: () => rootRouteImport,
} as any)
const TypeTypeRoute = TypeTypeRouteImport.update({
  id: '/type/$type',
  path: '/type/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncRoute = ApiCronSyncRouteImport.update({
  id: '/api/cron/sync',
  path: '/api/cron/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ThThTypeRoute = ThThTypeRouteImport.update({
  id: '/$type',
  path: '/$type',
  getParentRoute: () => ThThRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to': typeof HowToRoute
  '/latest': typeof LatestRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/base/$id': typeof BaseIdRoute
  '/th/$th': typeof ThThRouteWithChildren
  '/type/$type': typeof TypeTypeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/th/$th/$type': typeof ThThTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to': typeof HowToRoute
  '/latest': typeof LatestRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/base/$id': typeof BaseIdRoute
  '/th/$th': typeof ThThRouteWithChildren
  '/type/$type': typeof TypeTypeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/th/$th/$type': typeof ThThTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to': typeof HowToRoute
  '/latest': typeof LatestRoute
  '/popular': typeof PopularRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trending': typeof TrendingRoute
  '/base/$id': typeof BaseIdRoute
  '/th/$th': typeof ThThRouteWithChildren
  '/type/$type': typeof TypeTypeRoute
  '/api/cron/sync': typeof ApiCronSyncRoute
  '/th/$th/$type': typeof ThThTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-to'
    | '/latest'
    | '/popular'
    | '/search'
    | '/sitemap.xml'
    | '/trending'
    | '/base/$id'
    | '/th/$th'
    | '/type/$type'
    | '/api/cron/sync'
    | '/th/$th/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-to'
    | '/latest'
    | '/popular'
    | '/search'
    | '/sitemap.xml'
    | '/trending'
    | '/base/$id'
    | '/th/$th'
    | '/type/$type'
    | '/api/cron/sync'
    | '/th/$th/$type'
  id:
    | '__root__'
    | '/'
    | '/how-to'
    | '/latest'
    | '/popular'
    | '/search'
    | '/sitemap.xml'
    | '/trending'
    | '/base/$id'
    | '/th/$th'
    | '/type/$type'
    | '/api/cron/sync'
    | '/th/$th/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToRoute: typeof HowToRoute
  LatestRoute: typeof LatestRoute
  PopularRoute: typeof PopularRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrendingRoute: typeof TrendingRoute
  BaseIdRoute: typeof BaseIdRoute
  ThThRoute: typeof ThThRouteWithChildren
  TypeTypeRoute: typeof TypeTypeRoute
  ApiCronSyncRoute: typeof ApiCronSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to': {
      id: '/how-to'
      path: '/how-to'
      fullPath: '/how-to'
      preLoaderRoute: typeof HowToRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base/$id': {
      id: '/base/$id'
      path: '/base/$id'
      fullPath: '/base/$id'
      preLoaderRoute: typeof BaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/th/$th': {
      id: '/th/$th'
      path: '/th/$th'
      fullPath: '/th/$th'
      preLoaderRoute: typeof ThThRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/type/$type': {
      id: '/type/$type'
      path: '/type/$type'
      fullPath: '/type/$type'
      preLoaderRoute: typeof TypeTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync': {
      id: '/api/cron/sync'
      path: '/api/cron/sync'
      fullPath: '/api/cron/sync'
      preLoaderRoute: typeof ApiCronSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/th/$th/$type': {
      id: '/th/$th/$type'
      path: '/$type'
      fullPath: '/th/$th/$type'
      preLoaderRoute: typeof ThThTypeRouteImport
      parentRoute: typeof ThThRoute
    }
  }
}

interface ThThRouteChildren {
  ThThTypeRoute: typeof ThThTypeRoute
}

const ThThRouteChildren: ThThRouteChildren = {
  ThThTypeRoute: ThThTypeRoute,
}

const ThThRouteWithChildren = ThThRoute._addFileChildren(ThThRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToRoute: HowToRoute,
  LatestRoute: LatestRoute,
  PopularRoute: PopularRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrendingRoute: TrendingRoute,
  BaseIdRoute: BaseIdRoute,
  ThThRoute: ThThRouteWithChildren,
  TypeTypeRoute: TypeTypeRoute,
  ApiCronSyncRoute: ApiCronSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
